import { ProductProvider } from '@/context/ProductContext';
import { SystemProvider } from '@/context/SystemContext';
import type { Metadata } from 'next';
import './global.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
          <SystemProvider>
            <ProductProvider>{children}</ProductProvider>
          </SystemProvider>
      </body>
    </html>
  );
}
